FROM openjdk:11-jdk-slim as builder
ENV APP_HOME=/usr/app/
WORKDIR $APP_HOME
COPY build.gradle settings.gradle libraries.gradle gradlew $APP_HOME
COPY . .
RUN ./gradlew build

FROM openjdk:11
ARG PROJECT_NAME=spring-profile-logging
ARG PROJECT_VERSION=1.0-SNAPSHOT
ENV APP_HOME=/usr/app/
ENV APP_JAR_NAME=${PROJECT_NAME}-${PROJECT_VERSION}.jar
WORKDIR $APP_HOME
COPY --from=builder ${APP_HOME}/build/libs/${APP_JAR_NAME} .
CMD java ${JAVA_OPTS} -cp ${APP_JAR_NAME} -Dloader.main=com.mirowengner.example.producer.ProducerApp org.springframework.boot.loader.PropertiesLauncher
